### ISSUE TITLE
Challenge 1 

### ISSUE THREAD

**Issue by aeespinosao** [angular-medellin/challenges#1]
https://aeespinosao.github.io/Angular_Challenge_1/

**Comment by ghost** [comment]
Felicitaciones! @aeespinosao  ! :1st_place_medal: , hiciste el reto muy bien. :confetti_ball: 
Disculpa la tardanza para responder  :see_no_evil:
Que tal si compartes tu código con la comunidad y así mismo puedes recibir una retroalimentación :smile:

**Comment by aeespinosao** [comment]
code: https://github.com/aeespinosao/Angular_Challenge_1/tree/code/code

**Comment by ghost** [comment]
@aeespinosao  You Rock!!! , me gusto mucho tu solución :female_detective:  :confetti_ball: .. Utilizar sanitizer fue un buen toque. Felicitación hiciste muy bien el reto :clap: :heart_eyes:
