### ISSUE TITLE
Challenge 1: Random Faces

### ISSUE THREAD

**Issue by ErisoHV** [angular-medellin/challenges#10]
-> [Code](https://github.com/ErisoHV/angular-faces-challenge)
-> [Challenge](https://erisohv.github.io/angular-faces-challenge/)

**Comment by jdjuan** [comment]
@ErisoHV !

Qué creatividad! 😁 muy chévere el detalle del slider para cambiar el CSS. ¡Excelente!

También felicitaciones por usar un componente! 🎖 

Para la próxima considera usar tipos al declarar tus variables! 😁
