### ISSUE TITLE
Challenge 1 : Random Faces

### ISSUE THREAD

**Issue by carand315** [angular-medellin/challenges#11]
https://github.com/carand315/AM.Challenge1

**Comment by jdjuan** [comment]
Gran trabajo! @carand315  🥇 hiciste el reto muy bien 🎊 

Me gustó mucho la parte donde todos los parámetros son parametrizables! 👍 

Para la próxima puedes intentar usar tipos en tus variables! 

Nos vemos en el próximo reto!
