### ISSUE TITLE
Challenge 1

### ISSUE THREAD

**Issue by rdcs1** [angular-medellin/challenges#12]
Hello, I finished all the challenge, here is the code for the app.
https://github.com/rdcs1/Challenge1

I add also the app:
https://rdcs1.github.io/Challenge1/

This is my first web application ever made... don't judge me. Thanks

**Comment by jdjuan** [comment]
Hey @rdcs1 ! 💯 Well done buddy! 🏅 

I really liked how you managed to customize it even further! 👍 

Two quick improvements for the next time:

- Remember to add types to your variables, that's what TypeScript is about anyway 🙂
- And try to use arrow functions over anonymous functions, they are mostly better!

You are ready for the next challenge!

**Comment by rdcs1** [comment]
Okay, thank you for the review, I will read about it. I hope to do a better code in the next monthly challenge. Thank you again.
