### ISSUE TITLE
Angular Challenge 2

### ISSUE THREAD

**Issue by camiloHimura** [angular-medellin/challenges#16]
Hello, here is my code: 

https://github.com/camilo56/challengeAnimation

Very nice challenge.

**Comment by ghost** [comment]
Hey @camilo56 You rock!! 💯  you made a great work  🎊  .

All animations are perfect!! 😻 . I ❤️  the "hinge" effect, you did it so cool!! 😎 .

you maybe can do the logic of setting the variable in a method in the controller, that way if the name of variable change you have to change the code less times.
