### ISSUE TITLE
Angular Monthly Challenge 1+2

### ISSUE THREAD

**Issue by datruq** [angular-medellin/challenges#17]
Me puse al día e hice las dos pruebas que habían.

En cuanto a las animaciones tuve algunos problemas; Apenas estoy aprendiendo sobre el tema.

PD: solo pude sacar rotate como esta en el challenge, las otras animaciones las inventé y podrían ser los nuevos crazy time :sweat_smile:

Link: [https://github.com/datruq/Angular-RandomAnimation](url)

**Comment by ghost** [comment]
Hola!! @datruq , genial no hiciste uno sino dos retos, feliciaciones! :confetti_ball: :100: 

Excelente el uso del observable con el operador timer :sunglasses: , y si, creaste unas animaciones super locas :joy: buen trabajo :heart_eyes_cat:  , recuerda que puedes echarle una miradita  a las soluciones de otros miembros de la comunida, y no dudes en preguntarme las dudas que tengas :smiley: 

Creo que el servicio podría omitirse y la data de los faces ponerlo en un archivo mock or data y exportarla, recuerda limpiar el código de  los metodos que no uses al final  :bowtie:

**Comment by datruq** [comment]
@ltciro Muchas gracias por tus recomendaciones! 👌 

Las voy a tener en cuenta para la próxima como buenas practicas.
