### ISSUE TITLE
Challenge 2 Accepted

### ISSUE THREAD

**Issue by santiagocano6** [angular-medellin/challenges#18]
It was nice, I learned about animations.

[Code](https://github.com/santiagocano6/NgMedellinFaceChallenge2)

**Comment by ghost** [comment]
Hey @santiagocano6  what a great solutions :heart_eyes_cat: , congratulations :confetti_ball: .

Great use of callbacks animations for hidden elements, all animations are perfect :sunglasses: and your code is very clean.

I invite you to look at the other solutions.
