### ISSUE TITLE
Challenge 2 

### ISSUE THREAD

**Issue by EsneiderSM** [angular-medellin/challenges#19]
Hi, I share my solution and the code! 👍

Solution: https://esneidersm.github.io/Angular-Med-Challenges
Code: https://github.com/EsneiderSM/Angular-Med-Challenges

**Comment by ghost** [comment]
Very good @EsneiderSM  ! :grin: 

Excellent code, well organized and readable! :100: , All animations are perfect :heart_eyes_cat: 

Pro tip: next time you can create  an only method that have the responsibility of change the value in the variable state and send as parameter the value, this would do your code a little more clean.
