### ISSUE TITLE
Challenge 3, Chuck Norris Joke

### ISSUE THREAD

**Issue by cmariofonseca** [angular-medellin/challenges#21]
Hi guys, this is my code
https://github.com/cmariofonseca/Chanllege3/tree/master/chuckNorrisJoke

**Comment by ghost** [comment]
Hi @cmariofonseca  :1st_place_medal: , You are the first one... Congratulations :confetti_ball: 

Great solution  :heart_eyes_cat: , a little tip, you can import only the operator that you use,  like
 ``` import 'rxjs/add/operator/map'; ```   and reduce the charge of the files.
