### ISSUE TITLE
Challenge 3 accepted

### ISSUE THREAD

**Issue by santiagocano6** [angular-medellin/challenges#22]
Hi, here it is!!!

**Code**: [Review me!](https://github.com/santiagocano6/NgMedellinChallenge3ChuckNorrisJokes)
**Deployed**: [Look me!](https://santiagocano6.github.io/)

**Comment by ghost** [comment]
Wow Wow  @santiagocano6 !!!! very nice code and solutions :confetti_ball: :nerd_face: 

viewed and reviewed!!, very clean code.
