### ISSUE TITLE
my solution to challenge

### ISSUE THREAD

**Issue by eseguro** [angular-medellin/challenges#25]
https://github.com/eseguro/JokeChallenge

Thanks for all support!

**Comment by ghost** [comment]
Hi @eseguro, wow what a great solution  :neckbeard: :100: 

I :heart:  your code, very clean, great use of RxJS, :confetti_ball: 

a little tip, you can import only the operator that you use, in your case :
```js
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/mergeMap';

```
and reduce the charge of the files.
