### ISSUE TITLE
Angular Challenge: Chuck Norris Jokes

### ISSUE THREAD

**Issue by uribejuanda** [angular-medellin/challenges#26]
Hi everyone, here is my solution https://github.com/uribejuanda/chuckNorrisFacts
and Demo [**here**](https://uribejuanda.github.io/chuckNorrisFacts/)

**Comment by ghost** [comment]
Wow Wow @uribejuanda  !!!! very nice code and solution :confetti_ball: :nerd_face:

I :heart:  your code, very clean code. 

Great job, buddy. :heart_eyes_cat:

**Comment by uribejuanda** [comment]
Thx @ltciro !! :)
