### ISSUE TITLE
Challenge solution.

### ISSUE THREAD

**Issue by leono286** [angular-medellin/challenges#27]
Hi!! this is my solution 🎉🎉:

**code**: https://github.com/leono286/AngularChallengeChuckNorrisJoke

**live**:  https://leono286.github.io/AngularChallengeChuckNorrisJoke

Thanks!!

**Comment by ghost** [comment]
Yay!! @leono286  great solution. :confetti_ball:  :100: 

very clean code , the counter was a nice touch.

Thank you for participating in the challenges :heart_eyes_cat:
