### ISSUE TITLE
My Challenge 3 Chuck Jokes

### ISSUE THREAD

**Issue by mcada01** [angular-medellin/challenges#28]
https://github.com/mcada01/Challenge3.git

**Comment by ghost** [comment]
Wow Wow  @mcada01  :confetti_ball:   Veo que es tu primer repo en GitHub! Genial! :call_me_hand: :heart_eyes_cat: 

Super cool tu solución :sunglasses: . tienes un código muy organizado e hiciste un gran uso de los operadores de RxJS :heart: ,   no conocía la forma de crear el observable :nerd_face: 
```js 
IntervalObservable.create
```
:+1:  excelente! la otra forma para crearlo sería : 

```js
Observable.interval (6000)
```

Es muy emocionante que participes de los desafíos!! :tada:
