### ISSUE TITLE
Chuck Norris Challenge

### ISSUE THREAD

**Issue by suarezquiroz** [angular-medellin/challenges#31]
https://github.com/suarezquiroz/chuck-norris

//start:    2017-10-28T17:36:57.929Z
//finish:   2017-10-28T18:10:20.068Z

by Santiago Suarez Quiroz

**Comment by ltciro** [comment]
Hi @suarezquiroz! :bell: :ghost:

Great work! 🎊    you used HttpClient 👍
I invite you to check the solutions of other members of the community 🤓 

PD: Sorry for the delay, Merry Christmas 🎅 🎄
