### ISSUE TITLE
Angular Challenge: Random Face

### ISSUE THREAD

**Issue by Bilaltariq98** [angular-medellin/challenges#32]
Hi!

Below is my solution to the challenge! This is my first angular app that I'm trying without following any tutorials! 

https://github.com/Bilaltariq98/randomface

Thanks for the challenges!

**Comment by ltciro** [comment]
Hey @Bilaltariq98, congrats on your first ng App 🎊 💯 .
You did a great work! ✅ 👏 

Remember to clean your code 👻 , like remove imports not be used like RxJS and I think that setInterval import is unnecessary, I would love to know if you import it for some reason.

PD: Sorry for the delay, Merry Christmas 🎅 🎄
