### ISSUE TITLE
Random face challenge #1

### ISSUE THREAD

**Issue by EsneiderSM** [angular-medellin/challenges#4]
https://esneidersm.github.io/Random-Face-Challenge/

**Comment by ghost** [comment]
Felicitaciones @EsneiderSM!, hiciste muy bien el reto! :confetti_ball: y tienes un código muy limpio :medal_sports: . excelente detalle el cuerpo con NG :heart:  jeje :joy_cat:

**Comment by EsneiderSM** [comment]
Hola @ltciro, muchas gracias por tus comentarios, la idea es ir mejorando cada día mas, excelente que te gusto lo del cuerpo, jajajaja
