### ISSUE TITLE
Random Face, Challange 1 Finished 

### ISSUE THREAD

**Issue by emerdeveloper** [angular-medellin/challenges#5]
https://emerdeveloper.github.io/randomFaceChallengeAM/dist/

**Comment by ghost** [comment]
:vulcan_salute:  Hola @emerdeveloper ! Excelente trabajo con el reto! :confetti_ball: tienes un código muy limpio :heart_eyes:   Me gusto mucho que creaste un componente :neckbeard: , la próxima puedes agregar el sufijo  ".componente" al nombre de los archivos de la carpeta face para identificar mejor que son de un componente Ej. ``` face.component.ts, face.component.css face.component.html ``` :cat:

**Comment by emerdeveloper** [comment]
Hola @ltciro Gracias a ti por la observación lo tendré muy presente.
