### ISSUE TITLE
🤘😀 Challenge completed

### ISSUE THREAD

**Issue by rojasjuniore** [angular-medellin/challenges#6]
[😀 Challenge completed](https://rojasjuniore.github.io/Angular-medellin-challenges-RandomFace/)
[ 💻 Code ](https://github.com/rojasjuniore/Angular-medellin-challenges-RandomFace)

**Comment by ghost** [comment]
@rojasjuniore You Rock!! :medal_sports:  Felicitaciones hiciste muy bien el reto y aparte con animación, keyframes :heart_eyes: :clap:  . Tienes un código muy organizado :confetti_ball:.  

Por cierto no te puedes perder el próximo meetup donde veremos animaciones! :sunglasses:

**Comment by rojasjuniore** [comment]
Gracias por la observación @ltciro.
![1](https://media.giphy.com/media/Q0M7IC1RgF56w/giphy.gif)

**Comment by rojasjuniore** [comment]
Hola @ltciro  cuando es el proximo meetup?

**Comment by jdjuan** [comment]
@rojasjuniore **[Aquí está!](https://www.meetup.com/Angular-Medellin/events/243162387/)** :octocat:  :octocat:  :octocat:

**Comment by rojasjuniore** [comment]
Gracias @jdjuan :)
