### ISSUE TITLE
Challenge accepted.

### ISSUE THREAD

**Issue by matew17** [angular-medellin/challenges#7]
Hi there, this is the code and web with the challenge solved.

Code:
https://github.com/matew17/random-faces

Web:
https://matew17.github.io/random-faces/ 

Thanks.

**Comment by jdjuan** [comment]
Well done @matew17 ! 👍 

I liked a lot the way you separated it into a component and a service, very pro of you! 😁 

Two small recommendations:
- Don't leave commented code unless you are gonna use it soon, it just clutters your code base. 
- Don't call methods or put logic in constructors, use ngInit instead 😄 

See you in the next challenge!
